### ISSUE TITLE
Corrupted Files

### ISSUE THREAD

**Issue by BlazeAccelerator** [xan1242/CIPTool#1]
I'm trying to extract the files of the card artworks, but the extracted files are all corrupt. Jpg files can't be viewed and gim files can't be viewed or extracted with programs like Noesis. Is there a problem or am I doing something wrong? I can't get the program to open with Command Prompt either. Thank you.

**Comment by xan1242** [comment]
How exactly are you using this utility? You're meant to launch it from a shell, so it should just work from there.

Also which game (and its region) and which files did you use to extract?

I used GimConv to convert the image to PNG and it worked just fine. Below is an example extracted from Tag Force 1 cardh_e.cip (by dragging and dropping the file into the tool through Windows Explorer).

![test](https://user-images.githubusercontent.com/8014093/175179157-7e8c2297-d85a-4bd8-8d31-c257aa6b0aca.png)

It should work for all formats except Tag Force Special's JPEGs which needs the '-s' argument to extract those.

**Comment by xan1242** [comment]
I've taken a look at Noesis and it indeed doesn't open the file. 

That is because the GIM header from the game isn't technically correct but official GimConv from Sony (and real PSP) doesn't really care about it so it just works.

GimConv throws this:

`WARNING : illegal image order 1`

Which seems to break whatever Noesis has, so just stick to tools based on GimConv.

**Comment by BlazeAccelerator** [comment]
I'm trying to extract from the Japanese version of Tag Force Special actually. How do I extract those? Does dragging the files onto the exe still work?

I'm also having getting GimConv to work. I tried downloading it from two sources, but I can't get either to work from different problems.

**Comment by xan1242** [comment]
> I'm trying to extract from the Japanese version of Tag Force Special actually. How do I extract those? Does dragging the files onto the exe still work?

For Tag Force Special, you can drag and drop any CIP file except CARDJ_J.CIP which is the JPEG pack. For that you need to invoke the utility like this

`CIPTool -s CARDJ_J.CIP`

Then the JPEGs will also be properly extracted.

> I'm also having getting GimConv to work. I tried downloading it from two sources, but I can't get either to work from different problems.

You can find GimConv in RCOmage here: https://github.com/kakaroto/RCOMage/releases/tag/1.1.1

I'm not sure if there's a good GUI utility that you could use (there is [MinoriTool](https://github.com/noahc3/MinoriTool) I guess but that thing shouldn't even exist in the state that it does).

There is also [Gim Viewer](http://download.shadosoft-tm.com/GimViewerInstall.rar) which you could try using (but it doesn't support all formats, also Microsoft's SmartScreen screams at it, don't worry, it's safe).

EDIT: I guess Gim Viewer doesn't like the extracted images either, oh well...

**Comment by xan1242** [comment]
Also on another note - to extract with GimConv you need to invoke the utility something like this:

`gimconv 4007_0.gim -o 4007_0.png`

This will produce a proper png file.

**Comment by BlazeAccelerator** [comment]
I just downloaded GimConv again but had the same problem. When I open the program the command prompt ends with "press any key to continue" and when I do the prompt closes. 

For CARDJ_J.CIP do I change the file name to CIPTool -s CARDJ_J.CIP? How do I invoke the program as that?

**Comment by BlazeAccelerator** [comment]
Specifically, I'm trying to extract the higher quality card artworks. On the Yugioh Wikia there's art from the older games at 544x544px. I'm trying to find those artworks from TF Special.

**Comment by xan1242** [comment]
> For CARDJ_J.CIP do I change the file name to CIPTool -s CARDJ_J.CIP? How do I invoke the program as that?

This is exactly why I asked you this question:

> How exactly are you using this utility? You're meant to launch it from a shell, so it should just work from there.

So you have to launch and use it as a _command-line_ utility. This goes for gimconv as well!

Here are simple steps (assuming you're on Windows):

- Extract CIP files next to CIP tool
- In Explorer in that folder, hold SHIFT and right click in an empty spot
- In the context menu, select "Open PowerShell window here"
- Type in "cmd" to enter the command prompt
- Type in the command I wrote: `CIPTool -s CARDJ_J.CIP`

And you should end up with the extracted files (in a folder called CARDJ_J).

> Specifically, I'm trying to extract the higher quality card artworks. On the Yugioh Wikia there's art from the older games at 544x544px. I'm trying to find those artworks from TF Special.

Tag Force Special doesn't come with 544x544 images. It comes with 256x256 pictures.

Tag Force 3 has higher res of 512x512 (and are currently, to my knowledge, the highest quality digital artwork we have available, without censoring or watermarking).

For JPEGs, you don't even need the gimconv tool. They should already be in JPEG when extracted, so you should be able to open them with an image viewer just fine.

Where the Wikia got them from though, I have no idea...

(Sorry if I sound patronizing, just want to help!)

**Comment by xan1242** [comment]
Also it's CARDJ_A.CIP in Tag Force 3. For Special it's CARDJ256_A.CIP or something like that (I can't remember, I don't have the game at hand). (so wherever I typed in CARDJ_J.CIP previously just use CARDJ_A.CIP instead)

**Comment by BlazeAccelerator** [comment]
It's no problem. I really appreciate you taking the time to explain all this. I'm not very knowledgeable with command prompt stuff.

I finally got it to work with the Power Shell and got all of the jpg files. It's really unfortunate Special only has 256x256 images. I was hoping to get decent sized images of some of the artworks that have never been used anywhere else like the World Championship prize cards. But it's great to have the 512x512 images of the anime exclusive cards since they still look decent up scaled for the wallpapers I make.

Also, Noesis works for converting the other gim files in the game, but it can't do them as a batch. Can GimConv do that?

**Comment by xan1242** [comment]
> Also, Noesis works for converting the other gim files in the game, but it can't do them as a batch. Can GimConv do that?

Technically it can. As it is a command-line utility, the batch processing is done by the means of a script file (Windows has it, it's called a .bat or Batch file, or PowerShell scripts like .ps1 files). This is a bit of a complicated method to make on your own, but a very effective one.

If you need it, I could write up a script for you that can handle it. (It'll have to wait for a little while before I can do that though)

I think there may be also some tools floating around the internet that also handle batch processing of GIMs but I can't seem to find them right now (except that MinoriTool I mentioned previously).

> But it's great to have the 512x512 images of the anime exclusive cards since they still look decent up scaled for the wallpapers I make.

Offtopic - I've had great results with Cupscale and a few upscaling models (such as Lollipop and Ultra Yandere). You can use that to get some decently upscaled stuff!

**Comment by Dinoguy1000** [comment]
> > Specifically, I'm trying to extract the higher quality card artworks. On the Yugioh Wikia there's art from the older games at 544x544px. I'm trying to find those artworks from TF Special.
> 
> Tag Force Special doesn't come with 544x544 images. It comes with 256x256 pictures.
> 
> Tag Force 3 has higher res of 512x512 (and are currently, to my knowledge, the highest quality digital artwork we have available, without censoring or watermarking).

For context, the Tag Force artworks uploaded to the YGO wiki were captured in-game and stitched together (since apparently when you view the full artworks, you can only see a quarter of the artwork at a time; this must have been very tedious indeed for the thousands of artworks across the series!), which is why they're over-resolution. At some point we intend to extract the artworks directly from the game files and upload replacements (this will also allow us to replace a bunch of JPEGs with PNGs which is something we're a bit particular about), it's just a matter of doing.

(Full disclosure: I'm an editor on Yugipedia, not the YGO Wikia, but I *was* an editor on there for almost a decade before Yugipedia forked from there.)

**Comment by xan1242** [comment]
Pretty cool!

> At some point we intend to extract the artworks directly from the game files and upload replacements (this will also allow us to replace a bunch of JPEGs with PNGs which is something we're a bit particular about), it's just a matter of doing.

Feel free to use this tool then! I've made it for this exact purpose (and among other stuff, modding the game).

A bit more technical info - the image data in the game is stored in JPEG with 4:2:0 subsampling. You won't get anything in terms of quality by converting it to PNG (unless you're doing web related optimizations, then I understand).

The filenames are Card IDs, which are the internal Konami IDs used in their database. (so 4007 = [Blue Eyes White Dragon](https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=4007&request_locale=en))

(You can find it by editing the cid in the URL: https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=4007&request_locale=en - the **cid=4007** part)

The suffix ("_0" and "_1") denotes the alternative artworks available.

And lastly, all IDs before 4007 are temporary ones used for pre-release/game-exclusive/temporary/token cards.

I hope this will be helpful!

**Comment by Dinoguy1000** [comment]
> Feel free to use this tool then! I've made it for this exact purpose (and among other stuff, modding the game).

That's the plan! ;)

> A bit more technical info - the image data in the game is stored in JPEG with 4:2:0 subsampling. You won't get anything in terms of quality by converting it to PNG (unless you're doing web related optimizations, then I understand).

Aah right, the games using JPEG already, slipped my mind. In that case we'll be uploading them as JPEG, without conversion (though probably with a pass through a lossless filesize optimizer - unfortunately the options for optimizing JPEGs are somewhat slimmer than for lossless formats such as PNG).

> The filenames are Card IDs, which are the internal Konami IDs used in their database. (so 4007 = [Blue Eyes White Dragon](https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=4007&request_locale=en))
> 
> (You can find it by editing the cid in the URL: https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=4007&request_locale=en - the **cid=4007** part)
> 
> The suffix ("_0" and "_1") denotes the alternative artworks available.
> 
> And lastly, all IDs before 4007 are temporary ones used for pre-release/game-exclusive/temporary/token cards.
> 
> I hope this will be helpful!

We did know all of this already, but a reminder never hurts. =)

**Comment by BlazeAccelerator** [comment]
> If you need it, I could write up a script for you that can handle it. (It'll have to wait for a little while before I can do that though)

That would be great if it's not too much trouble. It would certainly make things easier.

> Offtopic - I've had great results with Cupscale and a few upscaling models (such as Lollipop and Ultra Yandere). You can use that to get some decently upscaled stuff!

Thanks for the suggestion. I usually use Waifu2x, but I'll give this one a shot. Some are a little better than others.

**Comment by BlazeAccelerator** [comment]
> For context, the Tag Force artworks uploaded to the YGO wiki were captured in-game and stitched together

That's really cool. I can't imagine how much work that must have been.
Updating the images with pngs would be great.

**Comment by xan1242** [comment]
@BlazeAccelerator Hi! It's been a while... Sorry for taking this long, but it's better late then never.

Use the tool I attached in this post. I included instructions on how to use it inside.

[BatchGimConv.zip](https://github.com/xan1242/CIPTool/files/9366570/BatchGimConv.zip)

I'll include this utility in the release as well so people don't wander around.
