### ISSUE TITLE
Question about repacking .cip file

### ISSUE THREAD

**Issue by BastionMizawa** [xan1242/CIPTool#3]
Hello, first of all, thank you for these incredible tools to modify the game, they are very useful, I just have a problem to repacking all the modified .gim images and form the new .cip file, I did not find a way to do it or what is it the series of commands that I should use, I am very beginner in this and I don't know how to do it, I would greatly appreciate your help. Greetings
ps: Sorry for my bad english, it is not my native language

**Comment by xan1242** [comment]
This is a command-line tool, so you have to use the terminal (cmd in Windows).

To pack a CIP back, you need to execute the tool like this:

`ciptool -p PathToFolder MyNewCIP.cip`

Where `PathToFolder` is the entire path to the folder containing the GIM files. For example:

`ciptool -p D:\cards cardh_j.cip`

If you need to pack the `cardm` file, you would simply use the `-pm` option instead. Example:

`ciptool -pm D:\cards_m cardm_j.cip`

If you need to pack the `cardj` file, you can use the `-pj` option instead. Keep in mind that these need to be jpg images. Example:

`ciptool -pj D:\cards_j cardj_j.cip`


I need to eventually rewrite the utility with better code and maybe a GUI to make things easier, but this shouldn't be too hard to use as-is.

**Comment by BastionMizawa** [comment]
Thank you very much for the quick reply! It worked like a charm. I was actually using that same command but using -w instead of -p , based on the sound tool where -w was used, there was my error 😅

**Comment by xan1242** [comment]
Remember - you can always launch the program without arguments to get more info.

I usually leave usage messages if they're not too complicated.
